name: "Chromatic"

# on:
#   push:
#     branches:
#       - migrate-version-latest # Only run on library changes
#     paths-ignore:
#       - 'libs/**/src/**/*.spec.ts'
#       - 'libs/**/src/**/*.spec.tsx'

on:
  pull_request:
    branches:
      - main # Only run on library changes
    paths-ignore:
      - 'libs/**/src/**/*.spec.ts'
      - 'libs/**/src/**/*.spec.tsx'


jobs:
  chromatic:
    runs-on: ubuntu-latest
    name: Run Chromatic
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: yarn install

      - name: Build Refined Mui Lib Storybook
        run: yarn nx run mui-latest:build-storybook

      - name: Publish Refined Mui Lib to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_MUI_LATEST }}
          workingDir: libs/ui/mui-latest
          storybookBuildDir:  /home/runner/work/ng-mono/ng-mono/dist/storybook/mui-latest
