name: "Chromatic"

on:
  push:
    branches:
      - libs/** # Only run on library changes
    paths-ignore:
      - 'libs/**/src/**/*.spec.ts'
      - 'libs/**/src/**/*.spec.tsx'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    name: Run Chromatic
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: yarn install

      - name: Build Mui Lib Storybook
        run: yarn nx run mui-lib:build-storybook

      - name: Publish Mui Lib to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_MUI_LIB }}
          workingDir: libs/mui-lib
          storybookBuildDir:  /home/runner/work/ng-mono/ng-mono/dist/storybook/mui-lib

      - name: Build Refined Mui Lib Storybook
        run: yarn nx run refined-mui-lib:build-storybook

      - name: Publish Refined Mui Lib to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_REFINED_MUI_LIB }}
          workingDir: libs/refined-mui-lib
          storybookBuildDir:  /home/runner/work/ng-mono/ng-mono/dist/storybook/refined-mui-lib
